{{- if .Values.ordersService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ordersService.name }}
  labels:
    app: {{ .Values.ordersService.name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ordersService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.ordersService.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ordersService.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Values.ordersService.name }}
        image: "{{ .Values.ordersService.image.repository }}:{{ .Values.ordersService.image.tag }}"
        imagePullPolicy: {{ .Values.ordersService.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ordersService.service.targetPort }}
        env:
        {{- range $key, $value := .Values.ordersService.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.ordersService.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ordersService.name }}
  labels:
    app: {{ .Values.ordersService.name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.ordersService.service.type }}
  ports:
  - port: {{ .Values.ordersService.service.port }}
    targetPort: {{ .Values.ordersService.service.targetPort }}
    protocol: TCP
  selector:
    app: {{ .Values.ordersService.name }}
    release: {{ .Release.Name }}
{{- end }}